app/main/forms.py
from flask_wtf import FlaskForm
from govuk_frontend_wtf.wtforms_widgets import GovRadioInput, GovSubmitInput, GovDateInput
from wtforms.fields import RadioField, SubmitField, DateField
from wtforms.validators import InputRequired


class CookiesForm(FlaskForm):
    functional = RadioField(
        "Do you want to accept functional cookies?",
        widget=GovRadioInput(),
        validators=[InputRequired(message="Select yes if you want to accept functional cookies")],
        choices=[("no", "No"), ("yes", "Yes")],
        default="no",
    )
    analytics = RadioField(
        "Do you want to accept analytics cookies?",
        widget=GovRadioInput(),
        validators=[InputRequired(message="Select yes if you want to accept analytics cookies")],
        choices=[("no", "No"), ("yes", "Yes")],
        default="no",
    )
    save = SubmitField("Save cookie settings", widget=GovSubmitInput())


class CircuitsForm(FlaskForm):

    circuits_date = DateField(
                "Please enter the start date for the period you need data for",
                widget=GovDateInput(),
                format="%d %m %Y",
                validators=[
                    InputRequired()
                ]
            )
    choose_session_effort = RadioField(
        "Choose session tpe",
        widget=GovRadioInput(),
        validators=[InputRequired(message="Choose an session you want to do")],
        choices=[("easy", "Easy set"), ("medium", "Medium effort"), ("hard", "Challenging")],
        default="no",
    )
    choose_session_type = RadioField(
        "Choose session tpe",
        widget=GovRadioInput(),
        validators=[InputRequired(message="Choose an session you want to do")],
        choices=[("Intervals", "HIIT"), ("AMPRAP", "12 by 12 by 6"), ("Minute_blasts", "One min by 6 by 3")],
        default="no",
    )

    submit = SubmitField("Continue", widget=GovSubmitInput())

app/__init__.py
from flask import Flask
from flask_assets import Bundle, Environment
from flask_compress import Compress
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from flask_talisman import Talisman
from flask_wtf.csrf import CSRFProtect
from govuk_frontend_wtf.main import WTFormsHelpers
from jinja2 import ChoiceLoader, PackageLoader, PrefixLoader

from config import Config

import gunicorn
gunicorn.SERVER = 'undisclosed'

assets = Environment()
compress = Compress()
csrf = CSRFProtect()
limiter = Limiter(key_func=get_remote_address, default_limits=["2 per second", "60 per minute"])
talisman = Talisman()


def create_app(config_class=Config):
    app = Flask(__name__, static_url_path="/assets")
    app.config.from_object(config_class)
    app.jinja_env.lstrip_blocks = True
    app.jinja_env.trim_blocks = True
    app.jinja_loader = ChoiceLoader(
        [
            PackageLoader("app"),
            PrefixLoader(
                {
                    "govuk_frontend_jinja": PackageLoader("govuk_frontend_jinja"),
                    "govuk_frontend_wtf": PackageLoader("govuk_frontend_wtf"),
                }
            ),
        ]
    )

    # Set content security policy
    csp = {
        "default-src": "'self'",
        "script-src": [
            "'self'",
            "'sha256-+6WnXIl4mbFTCARd8N3COQmT3bJJmo32N8q8ZSQAIcU='",
            "'sha256-l1eTVSK8DTnK8+yloud7wZUqFrI0atVo6VlC6PJvYaQ='",
        ],
    }

    # Initialise app extensions
    assets.init_app(app)
    compress.init_app(app)
    csrf.init_app(app)
    # limiter.init_app(app)
    # talisman.init_app(app, content_security_policy=csp)
    WTFormsHelpers(app)

    # Create static asset bundles
    css = Bundle("src/css/*.css", filters="cssmin", output="dist/css/custom-%(version)s.min.css")
    js = Bundle("src/js/*.js", filters="jsmin", output="dist/js/custom-%(version)s.min.js")
    if "css" not in assets:
        assets.register("css", css)
    if "js" not in assets:
        assets.register("js", js)

    # Register blueprints
    from app.main import bp as main_bp

    app.register_blueprint(main_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__, template_folder="../templates/main")

from app.main import routes  # noqa: E402,F401

app/main/routes.py
from flask import flash, json, make_response, render_template, request, redirect
from flask_wtf.csrf import CSRFError
from werkzeug.exceptions import HTTPException
from app.main import bp, workout
from app.main.forms import CookiesForm, CircuitsForm


@bp.route("/", methods=["GET", "POST"])
def index():
    form = CircuitsForm()
    if form.validate_on_submit():
        exercises = workout.get(form.choose_session_type.data, form.choose_session_effort.data)
        return render_template("results2.html", tables=exercises, form=form)

    return render_template("circuits_form.html", form=form)


@bp.route("/results", methods=["GET"])
def results():
    form = CircuitsForm()
    return render_template("results.html", form=form)

# @bp.route("/csv_results", methods=["GET"])
# def csv_results():
#     start_date = request.args['start_date']
#     end_date = request.args['end_date']
#     desired_url = request.args['desired_url']

#     start_date = datetime.strptime(start_date, '%Y%m%d')
#     end_date = datetime.strptime(end_date, '%Y%m%d')

#     df = get_csv_data(start_date, end_date, desired_url)

#     response = Response(df.to_csv())
#     response.headers["Content-Disposition"] = "attachment"
#     response.headers["Content-Type"] = "text/csv"
#     return response


@bp.route("/accessibility", methods=["GET"])
def accessibility():
    return render_template("accessibility.html")


@bp.route("/cookies", methods=["GET", "POST"])
def cookies():
    form = CookiesForm()
    # Default cookies policy to reject all categories of cookie
    cookies_policy = {"functional": "no", "analytics": "no"}

    if form.validate_on_submit():
        # Update cookies policy consent from form data
        cookies_policy["functional"] = form.functional.data
        cookies_policy["analytics"] = form.analytics.data

        # Create flash message confirmation before rendering template
        flash("You’ve set your cookie preferences.", "success")

        # Create the response so we can set the cookie before returning
        response = make_response(render_template("cookies.html", form=form))

        # Set cookies policy for one year
        response.set_cookie("cookies_policy", json.dumps(cookies_policy), max_age=31557600)
        return response
    elif request.method == "GET":
        if request.cookies.get("cookies_policy"):
            # Set cookie consent radios to current consent
            cookies_policy = json.loads(request.cookies.get("cookies_policy"))
            form.functional.data = cookies_policy["functional"]
            form.analytics.data = cookies_policy["analytics"]
        else:
            # If conset not previously set, use default "no" policy
            form.functional.data = cookies_policy["functional"]
            form.analytics.data = cookies_policy["analytics"]
    return render_template("cookies.html", form=form)


@bp.route("/privacy", methods=["GET"])
def privacy():
    return render_template("privacy.html")


@bp.app_errorhandler(HTTPException)
def http_exception(error):
    return render_template(f"{error.code}.html"), error.code


@bp.app_errorhandler(CSRFError)
def csrf_error(error):
    flash("The form you were submitting has expired. Please try again.")
    return redirect(request.full_path)


@bp.after_request
def add_security_headers(resp):
    csp = "default-src 'self'; script-src 'self' 'sha256-+6WnXIl4mbFTCARd8N3COQmT3bJJmo32N8q8ZSQAIcU=' 'sha256-l1eTVSK8DTnK8+yloud7wZUqFrI0atVo6VlC6PJvYaQ=';"
    resp.headers['Content-Security-Policy'] = csp
    return resp

app/templates/base.html
{% extends 'govuk_frontend_jinja/template.html' %}

{%- from 'govuk_frontend_jinja/components/cookie-banner/macro.html' import govukCookieBanner-%}
{%- from 'govuk_frontend_jinja/components/error-summary/macro.html' import govukErrorSummary-%}
{%- from 'govuk_frontend_jinja/components/notification-banner/macro.html' import govukNotificationBanner -%}
{%- from 'govuk_frontend_jinja/components/phase-banner/macro.html' import govukPhaseBanner -%}

{% set assetPath = url_for('static', filename='').rstrip('/') %}

{% block pageTitle %}{{config['SERVICE_NAME']}} – GOV.UK{% endblock %}

{% block head %}
  <meta name="description" content="{{config['SERVICE_NAME']}}">
  <meta name="keywords" content="GOV.UK, govuk, gov, government, uk, frontend, ui, user interface, jinja, python, flask, port, template, templating, macro, component, design system, html, forms, wtf, wtforms, widget, widgets, demo, example">
  <meta name="author" content="{{config['DEPARTMENT_NAME']}}">
  <!--[if gt IE 8]><!--><link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='govuk-frontend-4.4.1.min.css') }}" /><!--<![endif]-->
  <!--[if IE 8]><link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='govuk-frontend-ie8-4.4.1.min.css') }}" /><![endif]-->
  {% assets "css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
{% endblock %}

{% block bodyStart %}
  {% if "cookies_policy" not in request.cookies %}
    {% set html %}
      <p class="govuk-body">We use some essential cookies to make this service work.</p>
      <p class="govuk-body">We’d like to set additional cookies so we can remember your settings, understand how people use the service and make improvements.</p>
    {% endset %}

    {% set acceptHtml %}
      <p class="govuk-body">You’ve accepted additional cookies. You can <a class="govuk-link" href="{{ url_for('main.cookies') }}">change your cookie settings</a> at any time.</p>
    {% endset %}

    {% set rejectHtml %}
      <p class="govuk-body">You’ve rejected additional cookies. You can <a class="govuk-link" href="{{ url_for('main.cookies') }}">change your cookie settings</a> at any time.</p>
    {% endset %}

    {{ govukCookieBanner({
      'ariaLabel': "Cookies on " + config['SERVICE_NAME'],
      'attributes': {
        'id': "cookie-banner"
      },
      'messages': [
        {
          'attributes': {
            'id': "default-message"
          },
          'headingText': "Cookies on " + config['SERVICE_NAME'],
          'html': html,
          'actions': [
            {
              'attributes': {
                'id': "accept-cookies"
              },
              'text': "Accept additional cookies",
              'type': "button",
              'name': "cookies",
              'value': "accept"
            },
            {
              'attributes': {
                'id': "reject-cookies"
              },
              'text': "Reject additional cookies",
              'type': "button",
              'name': "cookies",
              'value': "reject"
            },
            {
              'text': "View cookies",
              'href': url_for('main.cookies')
            }
          ]
        },
        {
          'attributes': {
            'id': "accepted-message"
          },
          'html': acceptHtml,
          'role': "alert",
          'hidden': true,
          'actions': [
            {
              'attributes': {
                'id': "accepted-hide"
              },
              'text': "Hide this message"
            }
          ]
        },
        {
          'attributes': {
            'id': "rejected-message"
          },
          'html': rejectHtml,
          'role': "alert",
          'hidden': true,
          'actions': [
            {
              'attributes': {
                'id': "rejected-hide"
              },
              'text': "Hide this message"
            }
          ]
        }
      ]
    }) }}
  {% endif %}
{% endblock %}

{% block header %}
  {{ govukHeader({
    'homepageUrl': url_for('main.index'),
    'serviceName': config['SERVICE_NAME'],
    'serviceUrl': url_for('main.index')
  }) }}
{% endblock %}

{% block beforeContent %}
  {{ govukPhaseBanner({
    'tag': {
      'text': config['SERVICE_PHASE']
    },
    'html': 'This is a new service – your <a class="govuk-link" href="mailto:' + config['CONTACT_EMAIL'] +'?subject=Feedback">feedback</a> will help us to improve it.'
  }) }}
{% endblock %}

{% block content %}
  {% if form and form.errors %}
    {{ govukErrorSummary(wtforms_errors(form)) }}
  {% endif %}

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
          {{ govukNotificationBanner({'type': category, 'html': message}) }}
      {% endfor %}
    {% endif %}
  {% endwith %}
{% endblock %}

{% block footer %}
  {{ govukFooter({
    'meta': {
      'items': [
        {
          'href': url_for('main.accessibility'),
          'text': "Accessibility"
        },
        {
          'href': url_for('main.cookies'),
          'text': "Cookies"
        },
        {
            'href': url_for('main.privacy'),
            'text': "Privacy"
          }
      ],
      'html': 'Built by <a href="' + config['DEPARTMENT_URL'] +'" class="govuk-footer__link">' + config['DEPARTMENT_NAME'] + '</a>'
    }
  }) }}
{% endblock %}

{% block bodyEnd %}
  <!--[if gt IE 8]><!-->
  <script src="{{ url_for('static', filename='govuk-frontend-4.4.1.min.js') }}"> </script>
  <script>window.GOVUKFrontend.initAll()</script>
  <!--<![endif]-->
  {% assets "js" %}<script type="text/javascript" src="{{ ASSET_URL }}"></script>{% endassets %}
{% endblock %}

app/templates/main/429.html
{% extends "base.html" %}

{% block pageTitle %}Too many requests – {{config['SERVICE_NAME']}} – GOV.UK{% endblock %}

{% set mainClasses = "govuk-main-wrapper--l" %}

{% block content %}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-l">Sorry, there is a problem</h1>
        <p class="govuk-body">There have been too many attempts to access this page.</p>
        <p class="govuk-body">Try again later.</p>
    </div>
</div>
{% endblock %}

app/templates/main/503.html
{% extends "base.html" %}

{% block pageTitle %}Sorry, the service is unavailable – {{config['SERVICE_NAME']}} – GOV.UK{% endblock %}

{% set mainClasses = "govuk-main-wrapper--l" %}

{% block content %}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-l">Sorry, the service is unavailable</h1>
        <p class="govuk-body">You will be able to use the service from 9am on Monday 19&nbsp;November&nbsp;2018.</p>
    </div>
</div>
{% endblock %}

app/templates/main/blank.html
{{output}}

app/templates/main/circuits_form.html
{% extends "base.html" %}

{%- from 'govuk_frontend_jinja/components/error-summary/macro.html' import govukErrorSummary -%}
{%- from "govuk_frontend_jinja/components/date-input/macro.html" import govukDateInput -%}
{%- from "govuk_frontend_jinja/components/input/macro.html" import govukInput -%}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}
{%- from 'govuk_frontend_jinja/components/inset-text/macro.html' import govukInsetText -%}

{% block pageTitle %}{%- if form and form.errors %}Error: {% endif -%}Circuits session builder{% endblock %}

{% block content %}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
    {% if form.errors %}
        {{ govukErrorSummary(wtforms_errors(form)) }}
    {% endif %}

        <h1 class="govuk-heading-xl">GDS Circuits 2.0</h1>

<form action="" method="post" novalidate>
        {{ form.csrf_token }}

        {{ form.circuits_date(params={
          'type': 'string',
          'spellcheck': false
        }) }}
        {{ form.choose_session_effort(params={
         'type': 'string',
         'spellcheck': false
       }) }}
       {{ form.choose_session_type(params={
         'type': 'string',
         'spellcheck': false
       }) }}

           {{ form.submit }}
       </form>

    </div>
</div>
{% endblock %}

app/templates/main/cookies.html
{% extends "base.html" %}

{%- from 'govuk_frontend_jinja/components/back-link/macro.html' import govukBackLink -%}
{%- from 'govuk_frontend_jinja/components/table/macro.html' import govukTable -%}

{% block pageTitle %}{%- if form.errors %}Error: {% endif -%}Cookies – {{config['SERVICE_NAME']}} – GOV.UK{% endblock %}

{% block beforeContent %}
  {{ super() }}
  {{ govukBackLink({
    'text': "Back",
    'href': url_for('main.index')
  }) }}
{% endblock %}

{% block content %}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    {{ super() }}
    <h1 class="govuk-heading-l">Cookies</h1>
    <p class="govuk-body">Cookies are small files saved on your phone, tablet or computer when you visit a website.
    </p>
    <p class="govuk-body">We use cookies to make {{config['SERVICE_NAME']}} work and collect information about how you use our
      service.</p>

    <h2 class="govuk-heading-m">Essential cookies</h2>
    <p class="govuk-body">Essential cookies keep your information secure while you use {{config['SERVICE_NAME']}}. We do not need
      to ask permission to use them.</p>
    {{ govukTable(
      {
        'head': [{'text': 'Name'}, {'text': 'Purpose'}, {'text': 'Expires'}],
        'rows': [
          [{'text': 'cookie_policy'}, {'text': 'Saves your cookie consent settings'}, {'text': '1 year'}],
          [{'text': 'session'}, {'text': 'Temporary storage'}, {'text': 'Session'}]
        ]
      }
    )}}

    <h2 class="govuk-heading-m">Functional cookies</h2>
    <p class="govuk-body">Functional cookies allow you to take advantage of some functionality, for example remembering
      settings between visits. The service will work without them.</p>
    {{ govukTable(
      {
        'head': [{'text': 'Name'}, {'text': 'Purpose'}, {'text': 'Expires'}],
        'rows': [
          [{'text': 'foo'}, {'text': 'bar'}, {'text': 'baz'}]
        ]
      }
    )}}

    <h2 class="govuk-heading-m">Analytics cookies</h2>
    <p class="govuk-body">With your permission, we use Google Analytics to collect data about how you use {{config['SERVICE_NAME']}}. This
      information helps us to improve our service.</p>
    <p class="govuk-body">Google is not allowed to use or share our analytics data with anyone.</p>
    <p class="govuk-body">Google Analytics stores anonymised information about:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>how you got to {{config['SERVICE_NAME']}}</li>
      <li>the pages you visit on {{config['SERVICE_NAME']}} and how long you spend on them</li>
      <li>any errors you see while using {{config['SERVICE_NAME']}}</li>
    </ul>
    {{ govukTable(
      {
        'head': [{'text': 'Name'}, {'text': 'Purpose'}, {'text': 'Expires'}],
        'rows': [
          [{'text': 'foo'}, {'text': 'bar'}, {'text': 'baz'}]
        ]
      }
    )}}

    <h2 class="govuk-heading-m">Change your cookie settings</h2>
    <form action="" method="post" novalidate>
      {{ form.csrf_token }}
      {{ form.functional }}
      {{ form.analytics }}
      {{ form.save }}
    </form>
  </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{%- from "govuk_frontend_jinja/components/date-input/macro.html" import govukDateInput -%}
{%- from "govuk_frontend_jinja/components/input/macro.html" import govukInput -%}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}
{%- from 'govuk_frontend_jinja/components/inset-text/macro.html' import govukInsetText -%}
{% block beforeContent %}
{{ super() }}
{% endblock %}

{% block content %}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l">GDS Circuits 2.0</h1>

<form action="/results" method="post" novalidate>
        {{ form.csrf_token }}

{
           {{ form.circuits_date(params={
             'type': 'string',
             'spellcheck': false
           }) }}
           {{ form.choose_session_effort(params={
            'type': 'string',
            'spellcheck': false
          }) }}
          {{ form.choose_session_type(params={
            'type': 'string',
            'spellcheck': false
          }) }}


           {{ form.submit }}
       </form>

  </div>
</div>
{% endblock %}

app/templates/main/privacy.html
{% extends "base.html" %}

{%- from 'govuk_frontend_jinja/components/back-link/macro.html' import govukBackLink -%}

{% block pageTitle %}Privacy notice – {{config['SERVICE_NAME']}} – GOV.UK{% endblock %}

{% block beforeContent %}
  {{ super() }}
  {{ govukBackLink({
    'text': "Back",
    'href': url_for('main.index')
  }) }}
{% endblock %}

{% block content %}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        {{ super() }}
        <h1 class="govuk-heading-xl">Privacy notice</h1>
    </div>
</div>
{% endblock %}

app/templates/main/results.html
{% extends "base.html" %}
{%- from "govuk_frontend_jinja/components/table/macro.html" import govukTable -%}
{%- from 'govuk_frontend_jinja/components/error-summary/macro.html' import govukErrorSummary -%}
{%- from "govuk_frontend_jinja/components/date-input/macro.html" import govukDateInput -%}
{%- from "govuk_frontend_jinja/components/input/macro.html" import govukInput -%}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}
{%- from 'govuk_frontend_jinja/components/inset-text/macro.html' import govukInsetText -%}
{% block beforeContent %}
{{ super() }}
{% endblock %}

{% block content %}

<div class="govuk-width-container">
  <a href="#" class="govuk-back-link">Back</a>
  <main class="govuk-main-wrapper">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-one-third search-panel">
        <h2 class="govuk-heading-m">GDS Circuits 2.0</h2>
        <p class="govuk-body">Today's circuits session</p>

            <form action="" method="post" novalidate>
        {{ form.csrf_token }}


           {{ form.circuits_date(params={
             'type': 'string',
             'autocomplete': 'string',
             'spellcheck': false
           }) }}

           {{ form.submit }}
       </form>

      </div>
      <div class="govuk-grid-column-two-thirds">
              <h1 class="govuk-heading-l">Today's circuit session</h1>


{% set df_headers=[] %}
      {% for head_name in df_header %}
      {{ df_headers.append({ "text":head_name|safe }) or "" }}
      {% endfor %}

{% set rows=[] %}
{% for row in tables %}
    {% set cols = [] %}
      {% for col in row %}
      {{ cols.append({ "text": col|safe }) or "" }}
      {% endfor %}

      {{ rows.append(cols) or "" }}
{% endfor %}

{{ govukTable({
      "caption": "Exercises",
      "captionClasses": "govuk-table__caption--l",
      "firstCellIsHeader": true,
      "head": df_headers,
      "rows": rows
      })
      }}
          <p><a href="{{ csv_link }}" class="govuk-link">Download csv of the data</a></p>

  </div>
</div>
      </div>

    </div>
  </main>
</div>

{% endblock %}

app/templates/main/results2.html
{% extends "base.html" %}
{%- from "govuk_frontend_jinja/components/table/macro.html" import govukTable -%}
{%- from 'govuk_frontend_jinja/components/error-summary/macro.html' import govukErrorSummary -%}
{%- from "govuk_frontend_jinja/components/date-input/macro.html" import govukDateInput -%}
{%- from "govuk_frontend_jinja/components/input/macro.html" import govukInput -%}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}
{%- from 'govuk_frontend_jinja/components/inset-text/macro.html' import govukInsetText -%}
{% block beforeContent %}
{{ super() }}
{% endblock %}

{% block content %}

<div class="govuk-width-container">
  <a href="#" class="govuk-back-link">Back</a>
  <main class="govuk-main-wrapper">
    <div class="govuk-grid-row">

      <div class="govuk-grid-column-two-thirds">
              <h1 class="govuk-heading-l">Today's circuits session</h1>

{% set df_headers=[] %}
{{ df_headers.append({ "text":'Exercise'|safe }) or "" }}
{{ df_headers.append({ "text":'Description'|safe }) or "" }}
{{ df_headers.append({ "text":'Technique'|safe }) or "" }}
{{ df_headers.append({ "text":'Work'|safe }) or "" }}   
{{ df_headers.append({ "text":'Rest'|safe }) or "" }}               


{% set rows=[] %}
{% for row in tables %}
    {% set cols = [] %}

      {{ cols.append({ "text": row['Exercise_name']|safe }) or "" }}
      {{ cols.append({ "text": row['Description']|safe }) or "" }}
      {{ cols.append({ "text": row['Technique']|safe }) or "" }}
      {{ cols.append({ "text": row['work']|safe }) or "" }}
      {{ cols.append({ "text": row['rest']|safe }) or "" }}


      {{ rows.append(cols) or "" }}
{% endfor %}

{{ govukTable({
      "caption": "",
      "captionClasses": "govuk-table__caption--l",
      "firstCellIsHeader": true,
      "head": df_headers,
      "rows": rows
      })
      }}
          <p><a href="{{ csv_link }}" class="govuk-link">Download csv of the data</a></p>

  </div>
</div>
      </div>

    </div>
  </main>
</div>

{% endblock %}